# Generated by Django 3.2.20 on 2024-09-10 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('euth_maps', '0005_move_model_change_point_delete_areasettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MapIdea',
        ),
    ]
