# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-19 12:53
from __future__ import unicode_literals

from django.db import migrations, models
import euth.contrib.validators


class Migration(migrations.Migration):

    dependencies = [
        ('euth_offlinephases', '0005_copy_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offlineeventfileupload',
            name='document',
            field=models.FileField(upload_to='offlineevents/documents', validators=[
                euth.contrib.validators.validate_file_type_and_size]),
        ),
    ]
