# Generated by Django 3.2.20 on 2024-09-10 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('euth_offlinephases', '0007_auto_20240910_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offlinephase',
            name='phase',
        ),
        migrations.DeleteModel(
            name='FileUpload',
        ),
        migrations.DeleteModel(
            name='Offlinephase',
        ),
    ]
