name: "gunicorn"
type: "python:3.5"
disk: 256
hooks:
  build: |
    set -ex
    npm install --production
    npm run build
    pip install -r requirements.txt
    python ./manage.py collectstatic --noinput
  deploy: |
    set -ex
    python ./manage.py migrate --noinput
relationships:
  database: "database:postgresql"
variables:
  env:
    DJANGO_SETTINGS_MODULE: "euth_wagtail.settings.platform_sh"
mounts:
  "/media": "shared:files/media"
web:
  upstream:
    socket_family: "unix"
    protocol: "http"
  locations:
    "/":
      root: ""
      passthru: true
      allow: false
    "/static":
      root: "static/"
      allow: true
  commands:
    start: >
      gunicorn
      --workers=2
      --name=opin_dev
      --bind=unix:${SOCKET}
      euth_wagtail.wsgi
