# Generated by Django 3.2.20 on 2024-09-09 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('euth_actions', '0003_restrict_verbs_by_choices'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Action',
        ),
    ]
