# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-09 09:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipationModule',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('description', models.TextField()),
                ('date_start', models.DateTimeField(blank=True, null=True)),
                ('date_end', models.DateTimeField(blank=True, null=True)),
                ('module',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to='process.ParticipationModule')),
            ],
        ),
        migrations.CreateModel(
            name='PhaseType',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveSmallIntegerField(db_index=True)),
                ('moderator_permissions', models.ManyToManyField(
                    related_name='moderator_permissions', to='auth.Permission')),
                ('module_type', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('participant_permissions', models.ManyToManyField(
                    related_name='user_permissions', to='auth.Permission')),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=128, unique=True)),
                ('title', models.CharField(max_length=1024)),
                ('description', models.TextField()),
                ('moderators', models.ManyToManyField(
                    related_name='process_moderator', to=settings.AUTH_USER_MODEL)),
                ('participants',
                 models.ManyToManyField(blank=True,
                                        related_name='process_participant',
                                        to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='phase',
            name='phase_type',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='process.PhaseType'),
        ),
        migrations.AddField(
            model_name='participationmodule',
            name='process',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='process.Process'),
        ),
        migrations.AlterUniqueTogether(
            name='phasetype',
            unique_together=set(
                [('module_type', 'name'), ('module_type', 'order')]),
        ),
        migrations.AlterUniqueTogether(
            name='participationmodule',
            unique_together=set([('process', 'order')]),
        ),
    ]
