# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-14 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='slug',
            field=models.SlugField(editable=False, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='process',
            name='title',
            field=models.CharField(max_length=512),
        ),
    ]
