# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-14 13:31
from __future__ import unicode_literals
import re

from django.db import migrations, models

def forward_func(apps, schema_editor):
    Process = apps.get_model('process', 'Process')
    db_alias = schema_editor.connection.alias
    for process in Process.objects.using(db_alias).all():
        process.slug = re.sub('[^\w_-]', '', process.name, flags=re.ASCII)
        process.save()

def reverse_func(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('process', '0002_auto_20160614_1331'),
    ]

    operations = [
        migrations.RunPython(forward_func, reverse_func),
    ]
