# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-14 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0002_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process',
            name='name',
        ),
        migrations.AlterField(
            model_name='process',
            name='slug',
            field=models.SlugField(max_length=512, unique=True),
        ),
    ]
