# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-14 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0003_auto_20160614_1338'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='phase',
            unique_together=set([('phase_type', 'module')]),
        ),
    ]
