# Generated by Django 2.2.12 on 2020-05-27 10:00

import adhocracy4.images.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('euth_ideas', '0005_alter_idea_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='image',
            field=adhocracy4.images.fields.ConfiguredImageField('idea_image', blank=True, help_prefix='Please make sure the image is at least 400x200 px in dimensions and at most 5 MB in file size.', upload_to='ideas/images'),
        ),
    ]
