# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-26 12:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('euth_flashpoll', '0006_auto_20170124_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashpoll',
            name='module',
        ),
        migrations.DeleteModel(
            name='Flashpoll',
        ),
    ]
