# Generated by Django 2.2.3 on 2019-08-01 11:50

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import parler.fields


class Migration(migrations.Migration):

    dependencies = [
        ('euth_organisations', '0005_delete_title_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationtranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to=settings.A4_ORGANISATIONS_MODEL),
        ),
    ]
