# Generated by Django 3.2.20 on 2024-09-10 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('euth_organisations', '0006_update_parler_field'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='organisationtranslation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='organisationtranslation',
            name='master',
        ),
        migrations.DeleteModel(
            name='Organisation',
        ),
        migrations.DeleteModel(
            name='OrganisationTranslation',
        ),
    ]
