# Generated by Django 2.2.12 on 2020-04-24 14:15

import adhocracy4.categories.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('a4categories', '0002_category_icon'),
        ('euth_communitydebate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='category',
            field=adhocracy4.categories.fields.CategoryField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='a4categories.Category', verbose_name='Category'),
        ),
    ]
