# Generated by Django 3.2.20 on 2024-09-09 14:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('euth_communitydebate', '0004_topicfileupload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TopicFileUpload',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),

    ]
