# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-21 16:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailembeds.blocks
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0023_alter_page_revision_on_delete_behaviour'),
        ('wagtailimages', '0010_change_on_delete_behaviour'),
        ('home', '0003_simplepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='CarouselItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embed_url', models.URLField(blank=True, verbose_name='Embed URL')),
            ],
        ),
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Homepage'},
        ),
        migrations.AddField(
            model_name='homepage',
            name='body_da',
            field=wagtail.wagtailcore.fields.StreamField((('heading', wagtail.wagtailcore.blocks.CharBlock(classname='full title', icon='title')), ('paragraph', wagtail.wagtailcore.blocks.TextBlock(icon='pilcrow')), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock(icon='image')), ('info_block', wagtail.wagtailcore.blocks.StructBlock((('background_colour', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[('white', 'white'), ('black', 'black'), ('red', 'red')], default='white')), ('font_colour', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[('white', 'white'), ('black', 'black'), ('red', 'red')], default='black')), ('heading', wagtail.wagtailcore.blocks.TextBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock(required=False)), ('embedded_video', wagtail.wagtailembeds.blocks.EmbedBlock(required=False)), ('text', wagtail.wagtailcore.blocks.TextBlock()), ('internal_link', wagtail.wagtailcore.blocks.URLBlock(required=False)))))), blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='body_de',
            field=wagtail.wagtailcore.fields.StreamField((('heading', wagtail.wagtailcore.blocks.CharBlock(classname='full title', icon='title')), ('paragraph', wagtail.wagtailcore.blocks.TextBlock(icon='pilcrow')), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock(icon='image')), ('info_block', wagtail.wagtailcore.blocks.StructBlock((('background_colour', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[('white', 'white'), ('black', 'black'), ('red', 'red')], default='white')), ('font_colour', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[('white', 'white'), ('black', 'black'), ('red', 'red')], default='black')), ('heading', wagtail.wagtailcore.blocks.TextBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock(required=False)), ('embedded_video', wagtail.wagtailembeds.blocks.EmbedBlock(required=False)), ('text', wagtail.wagtailcore.blocks.TextBlock()), ('internal_link', wagtail.wagtailcore.blocks.URLBlock(required=False)))))), blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='body_en',
            field=wagtail.wagtailcore.fields.StreamField((('heading', wagtail.wagtailcore.blocks.CharBlock(classname='full title', icon='title')), ('paragraph', wagtail.wagtailcore.blocks.TextBlock(icon='pilcrow')), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock(icon='image')), ('info_block', wagtail.wagtailcore.blocks.StructBlock((('background_colour', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[('white', 'white'), ('black', 'black'), ('red', 'red')], default='white')), ('font_colour', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[('white', 'white'), ('black', 'black'), ('red', 'red')], default='black')), ('heading', wagtail.wagtailcore.blocks.TextBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock(required=False)), ('embedded_video', wagtail.wagtailembeds.blocks.EmbedBlock(required=False)), ('text', wagtail.wagtailcore.blocks.TextBlock()), ('internal_link', wagtail.wagtailcore.blocks.URLBlock(required=False)))))), null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='body_fr',
            field=wagtail.wagtailcore.fields.StreamField((('heading', wagtail.wagtailcore.blocks.CharBlock(classname='full title', icon='title')), ('paragraph', wagtail.wagtailcore.blocks.TextBlock(icon='pilcrow')), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock(icon='image')), ('info_block', wagtail.wagtailcore.blocks.StructBlock((('background_colour', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[('white', 'white'), ('black', 'black'), ('red', 'red')], default='white')), ('font_colour', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[('white', 'white'), ('black', 'black'), ('red', 'red')], default='black')), ('heading', wagtail.wagtailcore.blocks.TextBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock(required=False)), ('embedded_video', wagtail.wagtailembeds.blocks.EmbedBlock(required=False)), ('text', wagtail.wagtailcore.blocks.TextBlock()), ('internal_link', wagtail.wagtailcore.blocks.URLBlock(required=False)))))), blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='body_it',
            field=wagtail.wagtailcore.fields.StreamField((('heading', wagtail.wagtailcore.blocks.CharBlock(classname='full title', icon='title')), ('paragraph', wagtail.wagtailcore.blocks.TextBlock(icon='pilcrow')), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock(icon='image')), ('info_block', wagtail.wagtailcore.blocks.StructBlock((('background_colour', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[('white', 'white'), ('black', 'black'), ('red', 'red')], default='white')), ('font_colour', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[('white', 'white'), ('black', 'black'), ('red', 'red')], default='black')), ('heading', wagtail.wagtailcore.blocks.TextBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock(required=False)), ('embedded_video', wagtail.wagtailembeds.blocks.EmbedBlock(required=False)), ('text', wagtail.wagtailcore.blocks.TextBlock()), ('internal_link', wagtail.wagtailcore.blocks.URLBlock(required=False)))))), blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='body_sl',
            field=wagtail.wagtailcore.fields.StreamField((('heading', wagtail.wagtailcore.blocks.CharBlock(classname='full title', icon='title')), ('paragraph', wagtail.wagtailcore.blocks.TextBlock(icon='pilcrow')), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock(icon='image')), ('info_block', wagtail.wagtailcore.blocks.StructBlock((('background_colour', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[('white', 'white'), ('black', 'black'), ('red', 'red')], default='white')), ('font_colour', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[('white', 'white'), ('black', 'black'), ('red', 'red')], default='black')), ('heading', wagtail.wagtailcore.blocks.TextBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock(required=False)), ('embedded_video', wagtail.wagtailembeds.blocks.EmbedBlock(required=False)), ('text', wagtail.wagtailcore.blocks.TextBlock()), ('internal_link', wagtail.wagtailcore.blocks.URLBlock(required=False)))))), blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='body_sv',
            field=wagtail.wagtailcore.fields.StreamField((('heading', wagtail.wagtailcore.blocks.CharBlock(classname='full title', icon='title')), ('paragraph', wagtail.wagtailcore.blocks.TextBlock(icon='pilcrow')), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock(icon='image')), ('info_block', wagtail.wagtailcore.blocks.StructBlock((('background_colour', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[('white', 'white'), ('black', 'black'), ('red', 'red')], default='white')), ('font_colour', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[('white', 'white'), ('black', 'black'), ('red', 'red')], default='black')), ('heading', wagtail.wagtailcore.blocks.TextBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock(required=False)), ('embedded_video', wagtail.wagtailembeds.blocks.EmbedBlock(required=False)), ('text', wagtail.wagtailcore.blocks.TextBlock()), ('internal_link', wagtail.wagtailcore.blocks.URLBlock(required=False)))))), blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='title_da',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='title_de',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='title_en',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='title_fr',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='title_it',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='title_sl',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='title_sv',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='HomePageCarouselItem',
            fields=[
                ('carouselitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.CarouselItem')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='carousel_items', to='home.HomePage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
            bases=('home.carouselitem', models.Model),
        ),
        migrations.AddField(
            model_name='carouselitem',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
