# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 14:06
from __future__ import unicode_literals

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20160128_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body_da',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(classname='full title', icon='title')), ('paragraph', wagtail.blocks.TextBlock(icon='pilcrow')), ('image', wagtail.images.blocks.ImageChooserBlock(icon='image')), ('info_block', wagtail.blocks.StructBlock([(b'title', wagtail.blocks.CharBlock(classname=b'full title')), (b'image', wagtail.images.blocks.ImageChooserBlock(required=False)), (b'text', wagtail.blocks.TextBlock()), (b'button', wagtail.blocks.StructBlock([(b'internal_link', wagtail.blocks.PageChooserBlock(required=False)), (b'external_link', wagtail.blocks.URLBlock()), (b'link_text', wagtail.blocks.TextBlock())], required=False)), (b'highlight', wagtail.blocks.BooleanBlock(required=False))]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='body_de',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(classname='full title', icon='title')), ('paragraph', wagtail.blocks.TextBlock(icon='pilcrow')), ('image', wagtail.images.blocks.ImageChooserBlock(icon='image')), ('info_block', wagtail.blocks.StructBlock([(b'title', wagtail.blocks.CharBlock(classname=b'full title')), (b'image', wagtail.images.blocks.ImageChooserBlock(required=False)), (b'text', wagtail.blocks.TextBlock()), (b'button', wagtail.blocks.StructBlock([(b'internal_link', wagtail.blocks.PageChooserBlock(required=False)), (b'external_link', wagtail.blocks.URLBlock()), (b'link_text', wagtail.blocks.TextBlock())], required=False)), (b'highlight', wagtail.blocks.BooleanBlock(required=False))]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='body_en',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(classname='full title', icon='title')), ('paragraph', wagtail.blocks.TextBlock(icon='pilcrow')), ('image', wagtail.images.blocks.ImageChooserBlock(icon='image')), ('info_block', wagtail.blocks.StructBlock([(b'title', wagtail.blocks.CharBlock(classname=b'full title')), (b'image', wagtail.images.blocks.ImageChooserBlock(required=False)), (b'text', wagtail.blocks.TextBlock()), (b'button', wagtail.blocks.StructBlock([(b'internal_link', wagtail.blocks.PageChooserBlock(required=False)), (b'external_link', wagtail.blocks.URLBlock()), (b'link_text', wagtail.blocks.TextBlock())], required=False)), (b'highlight', wagtail.blocks.BooleanBlock(required=False))]))], null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='body_fr',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(classname='full title', icon='title')), ('paragraph', wagtail.blocks.TextBlock(icon='pilcrow')), ('image', wagtail.images.blocks.ImageChooserBlock(icon='image')), ('info_block', wagtail.blocks.StructBlock([(b'title', wagtail.blocks.CharBlock(classname=b'full title')), (b'image', wagtail.images.blocks.ImageChooserBlock(required=False)), (b'text', wagtail.blocks.TextBlock()), (b'button', wagtail.blocks.StructBlock([(b'internal_link', wagtail.blocks.PageChooserBlock(required=False)), (b'external_link', wagtail.blocks.URLBlock()), (b'link_text', wagtail.blocks.TextBlock())], required=False)), (b'highlight', wagtail.blocks.BooleanBlock(required=False))]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='body_it',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(classname='full title', icon='title')), ('paragraph', wagtail.blocks.TextBlock(icon='pilcrow')), ('image', wagtail.images.blocks.ImageChooserBlock(icon='image')), ('info_block', wagtail.blocks.StructBlock([(b'title', wagtail.blocks.CharBlock(classname=b'full title')), (b'image', wagtail.images.blocks.ImageChooserBlock(required=False)), (b'text', wagtail.blocks.TextBlock()), (b'button', wagtail.blocks.StructBlock([(b'internal_link', wagtail.blocks.PageChooserBlock(required=False)), (b'external_link', wagtail.blocks.URLBlock()), (b'link_text', wagtail.blocks.TextBlock())], required=False)), (b'highlight', wagtail.blocks.BooleanBlock(required=False))]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='body_sl',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(classname='full title', icon='title')), ('paragraph', wagtail.blocks.TextBlock(icon='pilcrow')), ('image', wagtail.images.blocks.ImageChooserBlock(icon='image')), ('info_block', wagtail.blocks.StructBlock([(b'title', wagtail.blocks.CharBlock(classname=b'full title')), (b'image', wagtail.images.blocks.ImageChooserBlock(required=False)), (b'text', wagtail.blocks.TextBlock()), (b'button', wagtail.blocks.StructBlock([(b'internal_link', wagtail.blocks.PageChooserBlock(required=False)), (b'external_link', wagtail.blocks.URLBlock()), (b'link_text', wagtail.blocks.TextBlock())], required=False)), (b'highlight', wagtail.blocks.BooleanBlock(required=False))]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='body_sv',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(classname='full title', icon='title')), ('paragraph', wagtail.blocks.TextBlock(icon='pilcrow')), ('image', wagtail.images.blocks.ImageChooserBlock(icon='image')), ('info_block', wagtail.blocks.StructBlock([(b'title', wagtail.blocks.CharBlock(classname=b'full title')), (b'image', wagtail.images.blocks.ImageChooserBlock(required=False)), (b'text', wagtail.blocks.TextBlock()), (b'button', wagtail.blocks.StructBlock([(b'internal_link', wagtail.blocks.PageChooserBlock(required=False)), (b'external_link', wagtail.blocks.URLBlock()), (b'link_text', wagtail.blocks.TextBlock())], required=False)), (b'highlight', wagtail.blocks.BooleanBlock(required=False))]))], blank=True, null=True),
        ),
    ]
