# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_add_fields_for_example_projects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='body_mt',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='body_ru',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='body_uk',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='intro_mt',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='intro_ru',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='intro_uk',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='title_mt',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='title_uk',
        ),
        migrations.RemoveField(
            model_name='manualsdetailpage',
            name='body_mt',
        ),
        migrations.RemoveField(
            model_name='manualsdetailpage',
            name='body_ru',
        ),
        migrations.RemoveField(
            model_name='manualsdetailpage',
            name='body_uk',
        ),
        migrations.RemoveField(
            model_name='manualsdetailpage',
            name='description_mt',
        ),
        migrations.RemoveField(
            model_name='manualsdetailpage',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='manualsdetailpage',
            name='description_uk',
        ),
        migrations.RemoveField(
            model_name='manualsdetailpage',
            name='title_mt',
        ),
        migrations.RemoveField(
            model_name='manualsdetailpage',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='manualsdetailpage',
            name='title_uk',
        ),
        migrations.RemoveField(
            model_name='manualsindex',
            name='body_mt',
        ),
        migrations.RemoveField(
            model_name='manualsindex',
            name='body_ru',
        ),
        migrations.RemoveField(
            model_name='manualsindex',
            name='body_uk',
        ),
        migrations.RemoveField(
            model_name='manualsindex',
            name='title_mt',
        ),
        migrations.RemoveField(
            model_name='manualsindex',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='manualsindex',
            name='title_uk',
        ),
        migrations.RemoveField(
            model_name='manualssectionpage',
            name='description_mt',
        ),
        migrations.RemoveField(
            model_name='manualssectionpage',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='manualssectionpage',
            name='description_uk',
        ),
        migrations.RemoveField(
            model_name='manualssectionpage',
            name='title_mt',
        ),
        migrations.RemoveField(
            model_name='manualssectionpage',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='manualssectionpage',
            name='title_uk',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='menu_title_mt',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='menu_title_ru',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='menu_title_uk',
        ),
        migrations.RemoveField(
            model_name='pagecollection',
            name='title_mt',
        ),
        migrations.RemoveField(
            model_name='pagecollection',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='pagecollection',
            name='title_uk',
        ),
        migrations.RemoveField(
            model_name='rssimport',
            name='rss_title_mt',
        ),
        migrations.RemoveField(
            model_name='rssimport',
            name='rss_title_ru',
        ),
        migrations.RemoveField(
            model_name='rssimport',
            name='rss_title_uk',
        ),
        migrations.RemoveField(
            model_name='simplepage',
            name='body_mt',
        ),
        migrations.RemoveField(
            model_name='simplepage',
            name='body_ru',
        ),
        migrations.RemoveField(
            model_name='simplepage',
            name='body_uk',
        ),
        migrations.RemoveField(
            model_name='simplepage',
            name='intro_mt',
        ),
        migrations.RemoveField(
            model_name='simplepage',
            name='intro_ru',
        ),
        migrations.RemoveField(
            model_name='simplepage',
            name='intro_uk',
        ),
        migrations.RemoveField(
            model_name='simplepage',
            name='title_mt',
        ),
        migrations.RemoveField(
            model_name='simplepage',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='simplepage',
            name='title_uk',
        ),
    ]
