# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-13 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_add_two_more_pages_to_page_collection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagecollection',
            old_name='intro_text',
            new_name='intro_text_de',
        ),
        migrations.AddField(
            model_name='pagecollection',
            name='intro_text_da',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='pagecollection',
            name='intro_text_el',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='pagecollection',
            name='intro_text_en',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pagecollection',
            name='intro_text_fr',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='pagecollection',
            name='intro_text_it',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='pagecollection',
            name='intro_text_ka',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='pagecollection',
            name='intro_text_mk',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='pagecollection',
            name='intro_text_sl',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='pagecollection',
            name='intro_text_sv',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
