# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-07 12:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0008_document_file_size'),
        ('home', '0034_remove_flashpoll_blueprints'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualssectionpage',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.Document'),
        ),
    ]
