# Generated by Django 2.2.12 on 2020-04-23 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('a4projects', '0026_project_project_type'),
        ('home', '0035_manualssectionpage_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='helppages',
            name='communitydebate',
            field=models.ForeignKey(blank=True, help_text='Please select an exemplary communitydebate project.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='example_project_communitydebate', to='a4projects.Project'),
        ),
    ]
