# Generated by Django 2.2.24 on 2021-07-15 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_helppages_communitydebate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='videoplayer_url',
        ),
    ]
