# Generated by Django 3.2.20 on 2024-09-09 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_add_use_json_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helppages',
            name='communitydebate',
        ),
    ]
