# Generated by Django 3.2.20 on 2024-09-10 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_remove_helppages_communitydebate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HelpPages',
        ),
    ]
