# Generated by Django 3.2.20 on 2024-09-10 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('euth_follows', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
