# Generated by Django 3.2.20 on 2024-10-23 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contrib', '0001_delete_a4_models'),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                "DROP TABLE IF EXISTS euth_ratings_rating",
            ],
            reverse_sql=migrations.RunSQL.noop,
        )
    ]
