# Generated by Django 3.2.20 on 2024-09-10 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('euth_memberships', '0002_add_invitations'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='request',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='request',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='request',
            name='project',
        ),
        migrations.DeleteModel(
            name='Invite',
        ),
        migrations.DeleteModel(
            name='Request',
        ),
    ]
