name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: Cache node modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Cache pip packages
        uses: actions/cache@v3
        env:
          cache-name: cache-pip-packages
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/requirements/dev.txt') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install Dependencies
        run: |
          npm install
          npm run build
          pip install -r requirements/dev.txt
          pip install coveralls
      - name: Run Tests
        run: |
          python manage.py collectstatic > /dev/null
          py.test --cov
          isort --diff -c euth_wagtail tests
          python manage.py makemigrations --dry-run --check --noinput
          flake8 euth_wagtail tests --exclude migrations,settings
          npm run lint
      - name: Coveralls
        env:
          GITHUB_TOKEN: ${{ secrets.COV }}
        run: |
          coveralls
      - name: Deploy
        if: github.ref == 'refs/heads/main'
        env:
          TRAVIS_SSH_SECRET: ${{ secrets.DEPLOY }}
        run: |
          ./scripts/deploy.sh
